"""empty message

Revision ID: 562517d5a202
Revises: c47199313c00
Create Date: 2023-05-25 19:38:02.718872

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '562517d5a202'
down_revision = 'c47199313c00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tuyen_sinh', schema=None) as batch_op:
        batch_op.alter_column('ten_nganh',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=1000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tuyen_sinh', schema=None) as batch_op:
        batch_op.alter_column('ten_nganh',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
