"""empty message

Revision ID: c47199313c00
Revises: 
Create Date: 2023-05-25 19:35:22.195008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c47199313c00'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tuyen_sinh',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ten_nganh', sa.String(length=100), nullable=True),
    sa.Column('khoa', sa.String(length=100), nullable=True),
    sa.Column('ma_chuyen_nganh', sa.String(length=50), nullable=True),
    sa.Column('chi_tieu', sa.Integer(), nullable=True),
    sa.Column('hoc_phi_du_kien', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tuyen_sinh')
    # ### end Alembic commands ###
